### ISSUE TITLE
Bars Disappear when clicked and dragged

### ISSUE THREAD

**Issue by Carl-Gustaf** [frappe/gantt#126] opened 2019-04-06 18:47 UTC
Same issue as #76, still not working for me

**Comment by partofthething** [comment] 2019-04-13 02:50
Same here. I get this behavior on the `index.html` that's provided in the repo. No errors or warnings on the console, just the regular log messages.

**Comment by WurstMitBrot** [comment] 2019-06-05 13:23
The problem is in the mouse events. The property offsetX, offsetY is causing the problem. I replaced it with clientX and clientY.

For example in bind_bar_events() 

            x_on_start = e.clientX;
            y_on_start = e.clientY;

**Comment by Carl-Gustaf** [comment] 2019-06-06 21:58
Hmm... I tried that but I can't get it to work :/ Could you share your snippet? @WurstMitBrot

**Comment by WurstMitBrot** [comment] 2019-06-07 08:09
Class Gantt:
     
    
           $.on(this.$svg, 'mousedown', '.bar-wrapper, .handle', (e, element) => {
            const bar_wrapper = $.closest('.bar-wrapper', element);

            //  make changing and dragging todos optional
            if (element.classList.contains('left') && this.options.enable_slide_edit) {
                is_resizing_left = true;
            } else if (element.classList.contains('right') && this.options.enable_slide_edit) {
                is_resizing_right = true;
            } else if (element.classList.contains('bar-wrapper') && this.options.enable_drag_edit) {
                is_dragging = true;
            }
            
            bar_wrapper.classList.add('active');
            //##############################################
            //  use clientX and Y offset doesn't work properly in firefox
            x_on_start = e.clientX;
            y_on_start = e.clientY;
            //#####################################################
            parent_bar_id = bar_wrapper.getAttribute('data-id');
            const ids = [
                parent_bar_id,
                ...this.get_all_dependent_tasks(parent_bar_id)
            ];
            bars = ids.map(id => this.get_bar(id));

            this.bar_being_dragged = parent_bar_id;

            bars.forEach(bar => {
                const $bar = bar.$bar;
                $bar.ox = $bar.getX();
                $bar.oy = $bar.getY();
                $bar.owidth = $bar.getWidth();
                $bar.finaldx = 0;
            });
        });

        $.on(this.$svg, 'mousemove', e => {
            if (!action_in_progress()) return;
            //####################################################
            //  use clientX and Y offset doesn't work properly in firefox
            const dx = e.clientX - x_on_start;
            const dy = e.clientY - y_on_start;
           //#####################################################
            bars.forEach(bar => {
                const $bar = bar.$bar;
                $bar.finaldx = this.get_snap_position(dx);

                if (is_resizing_left) {
                    if (parent_bar_id === bar.task.id) {
                        bar.update_bar_position({
                            x: $bar.ox + $bar.finaldx,
                            width: $bar.owidth - $bar.finaldx
                        });
                    } else {
                        bar.update_bar_position({
                            x: $bar.ox + $bar.finaldx
                        });
                    }
                } else if (is_resizing_right) {
                    if (parent_bar_id === bar.task.id) {
                        bar.update_bar_position({
                            width: $bar.owidth + $bar.finaldx
                        });
                    }
                } else if (is_dragging) {
                    bar.update_bar_position({ x: $bar.ox + $bar.finaldx });
                }
            });
        });






        bind_bar_progress() {
        let x_on_start = 0;
        let y_on_start = 0;
        let is_resizing = null;
        let bar = null;
        let $bar_progress = null;
        let $bar = null;

        $.on(this.$svg, 'mousedown', '.handle.progress', (e, handle) => {
            is_resizing = true;
            //##################################################
            //  use clientX and Y offset doesn't work properly in firefox
            x_on_start = e.clientX;
            y_on_start = e.clientY;
           //#####################################################
            const $bar_wrapper = $.closest('.bar-wrapper', handle);
            const id = $bar_wrapper.getAttribute('data-id');
            bar = this.get_bar(id);

            $bar_progress = bar.$bar_progress;
            $bar = bar.$bar;

            $bar_progress.finaldx = 0;
            $bar_progress.owidth = $bar_progress.getWidth();
            $bar_progress.min_dx = -$bar_progress.getWidth();
            $bar_progress.max_dx = $bar.getWidth() - $bar_progress.getWidth();
        });

        $.on(this.$svg, 'mousemove', e => {
            if (!is_resizing) return;
            //#####################################################
            //  use clientX and Y offset doesn't work properly in firefox
            let dx = e.clientX - x_on_start;
            let dy = e.clientY - y_on_start;
           //#####################################################

            if (dx > $bar_progress.max_dx) {
                dx = $bar_progress.max_dx;
            }
            if (dx < $bar_progress.min_dx) {
                dx = $bar_progress.min_dx;
            }

            const $handle = bar.$handle_progress;
            $.attr($bar_progress, 'width', $bar_progress.owidth + dx);
            $.attr($handle, 'points', bar.get_progress_polygon_points());
            $bar_progress.finaldx = dx;
        });

        $.on(this.$svg, 'mouseup', () => {
            is_resizing = false;
            if (!($bar_progress && $bar_progress.finaldx)) return;
            console.log("changed");
            
            //  reset value, otherwise event fires multiple times
            $bar_progress.finaldx = 0;
            bar.progress_changed();
            bar.set_action_completed();
        });
    }
`

**Comment by safwansamsudeen** [comment] 2024-04-05 11:21
This is very surprising. Do you still face this?

Closing this as this issue is going to turn 5 years old in a few days - apologies for the delay.

**Closed by safwansamsudeen** 2024-04-05 11:21 UTC
Labels: bug
