### ISSUE TITLE
Inline tasks

### ISSUE THREAD

**Issue by feliciaeponou** [frappe/gantt#172] opened 2020-03-16 10:44 UTC
![demo_5381_none-1](https://user-images.githubusercontent.com/42370369/76748459-b4794300-6772-11ea-9665-9f736beffc07.png)
I want to make inline tasks. Like on the picture. How can I deal with it ?

**Comment by ayushi-codal** [comment] 2020-03-25 08:28
> ![demo_5381_none-1](https://user-images.githubusercontent.com/42370369/76748459-b4794300-6772-11ea-9665-9f736beffc07.png)
> I want to make inline tasks. Like on the picture. How can I deal with it ?

Did you got Solution??

**Comment by JordanBinyon** [comment] 2020-03-25 09:46
In the `bar.js` class, there is a function that is responsible for calculating the Y position of the bar.

![image](https://user-images.githubusercontent.com/40386706/77522963-f7c36800-6e7c-11ea-929f-ae625c30702b.png)

In the code above, the `compute_y` function is using the index of the task to help decide the positioning. I haven't worked on a solution yet but it seems as though you would need to create a class that groups bars together and then alter the `computer_y` function to calculate the Y position using the group class's index instead of the bars index.

**Comment by qool** [comment] 2020-04-01 13:23
Duplicate of #95 - I'm also voting for the solution...

**Comment by KadKersani** [comment] 2020-10-29 09:21
Use the the custom_index  for all inline tasks..

**Comment by safwansamsudeen** [comment] 2024-04-05 13:54
Duplicate of #95 - this feature is a good one, will implement.

**Closed by safwansamsudeen** 2024-04-05 13:54 UTC
