### ISSUE TITLE
Is there a way to repeat the dates throughout the Gantt - or repeat at the bottom?

### ISSUE THREAD

**Issue by peterbournecommunications** [frappe/gantt#217] opened 2021-03-29 07:33 UTC
With long lists of entries in the chart we have to scroll back to see the date line at the top. Is it possible to add functionality to either repeat the dates every N lines, or just repeat the dates at the bottom at least?

**Comment by safwansamsudeen** [comment] 2024-04-04 20:55
What about a frozen header?

**Comment by safwansamsudeen** [comment] 2024-04-26 02:19
Duplicate of #115.

**Closed by safwansamsudeen** 2024-04-26 02:19 UTC
Labels: enhancement
