### ISSUE TITLE
Task start dates should be optional

### ISSUE THREAD

**Issue by 3hhh** [frappe/gantt#187] opened 2020-07-15 11:56 UTC
Usually tasks start when all of their dependencies are completed.

So if the start date is missing, one could easily compute it from the latest end date of the dependency tasks. If that's missing, one could error out.

Currently, tasks without start dates will produce strange boxes instead.

**Comment by safwansamsudeen** [comment] 2024-04-28 13:16
Duplicate of #293.

**Closed by safwansamsudeen** 2024-04-28 13:16 UTC
