### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by sirgalleto** [frappe/gantt#222] opened 2021-04-23 02:22 UTC
Hey! is there a config for using a read-only mode? Without the user able to change the task start/end date?

**Comment by mikeott** [comment] 2021-04-23 07:22
I don't think there is a setting for that, but you could easily do this within the CSS or with a line of jQuery.

```
.gantt .bar-wrapper {
    pointer-events: none;
}
```

...or if you prefer a jQuery alternative:

`$('.gantt .bar-wrapper').css('pointer-events', 'none');`

Either will prevent the tasks from being moved,

**Comment by djbpark1** [comment] 2021-08-10 19:25
A consequence of editing the CSS like that is it prevents the popup from appearing on click as well.

**Comment by Armxy** [comment] 2021-09-29 12:54
I'm adding this to the freppe-gantt/master/src/index.js:702

`
if(typeof bar.task.read_only !== 'undefined' && bar.task.read_only === true){
return;
}
`

then you only need to add read_only = true into a task that you want to be read-only.

**Comment by Igore-ADJOTIN** [comment] 2022-05-20 18:47
Hello. I was able to solve my problem by modifying the code. Look for the bind_events() function in the javascript file (dist/frappe-gantt.js), then comment on its content.

**Comment by safwansamsudeen** [comment] 2024-04-04 20:52
Duplicate of #323.

**Closed by safwansamsudeen** 2024-04-04 20:52 UTC
