### ISSUE TITLE
Cannot read property '$bar' of undefined

### ISSUE THREAD

**Issue by amir-xyz** [frappe/gantt#191] opened 2020-07-31 11:03 UTC
![Capture](https://user-images.githubusercontent.com/69039334/89029138-62b10e00-d34b-11ea-9cbb-faddd854b4ee.PNG)

No mouse events working on the chart

**Comment by wmandai** [comment] 2020-08-12 17:21
In my case this error was caused by using task **id** as **integers** changed to string and works. Maybe that helps someone.

**Comment by arnaudlevy** [comment] 2020-09-09 17:33
The example sets dependencies 'Task 2, Task 3' which do not exist. This causes that.

**Comment by wzulfikar** [comment] 2021-03-23 05:21
> In my case this error was caused by using task **id** as **integers** changed to string and works. Maybe that helps someone.

I can confirm. I changed my id from integer to string and it works.

**Comment by web-developer032** [comment] 2021-12-31 20:00
> The example sets dependencies 'Task 2, Task 3' which do not exist. This causes that.

Yes this is also tha cause.

**Comment by Messilimeng** [comment] 2022-04-07 14:43
My id is integers ,but  i do like this 
cant  work
   let dep_list = [];
     data.map((it) => {
          let jsons = {
            start: it.start_time,
            end: it.end_time,
            id: "" + it.id,
            org_id: it.id,
            lineNum: it.lineNum,
            state: it.state,
            name: "[" + it.name + "]" + it.mo_no,
            progress: Number((it.finish_num / it.num).toFixed(1)) * 100,
            custom_class: "cost-progress",
          };
          dep_list.push(jsons);
        });

        for (let item of dep_list) {
          if (item.state == 3) {
            let st = dep_list.find(
              (x) => x.lineNum == item.lineNum && x.state == 2
            );
            if (st != undefined && st != null) {
              item.dependencies = "" + st.org_id;
            } else {
              item.dependencies = "";
            }
          }
        }
can you tell me how to do that
![1649342573(1)](https://user-images.githubusercontent.com/12272166/162225833-e139e669-9489-472f-b8aa-c1ed69851133.png)

**Comment by safwansamsudeen** [comment] 2024-04-04 20:57
@Messilimeng do you still face this issue?

**Comment by safwansamsudeen** [comment] 2024-04-26 02:23
Fixed in #393.

**Closed by safwansamsudeen** 2024-04-26 02:23 UTC

**Comment by leslietquinn** [comment] 2024-11-14 06:18
> In my case this error was caused by using task **id** as **integers** changed to string and works. Maybe that helps someone.

I faced the same problem (with Inertia and React and Laravel) and I fixed it by casting the ID as a string in the model.
