### ISSUE TITLE
feature for fix the header when too much tasks is there

### ISSUE THREAD

**Issue by jeffersyuan1976** [frappe/gantt#316] opened 2023-03-29 02:53 UTC
Hi, 
If too much tasks is there, maybe we should thinking about to make the header fixed at the top of the gantt chart?
Thanks.

**Comment by m50S79sM6SRNp8Jn** [comment] 2023-08-20 12:44
I concur. Really this should be default behaviour since from the outset you would never know have many tasks would be part of the Gantt chart.

**Comment by safwansamsudeen** [comment] 2024-04-05 11:18
Yup - a sticky header is a good feature to have. Duplicate of #115.

**Closed by safwansamsudeen** 2024-04-05 11:18 UTC
