### ISSUE TITLE
Please consider Bar pinned on scroll 

### ISSUE THREAD

**Issue by zepvalue** [frappe/gantt#258] opened 2022-02-24 17:40 UTC
I would love to propose the bar being pinned on scroll so the user don't lose track of what day/month they are looking at ! 

If it's a feature that most users need would be happy to help implementing it :)

**Comment by m50S79sM6SRNp8Jn** [comment] 2023-08-19 09:31
Do you have such an example? Able to paste the image in the comments?

**Comment by safwansamsudeen** [comment] 2024-04-05 14:12
Duplicate of #115, I believe.

**Closed by safwansamsudeen** 2024-04-05 14:12 UTC
