### ISSUE TITLE
It is possible to assign the same ressource more than one time to the same task bug/feature ?

### ISSUE THREAD

**Issue by pidou46** [frappe/gantt#254] opened 2022-01-28 16:28 UTC
It is possible to assign assign the same resource more than one time to the same task.

Is this bug or a feature ? I don't see use a case but I may be wrong...

**Comment by dresende** [comment] 2022-07-27 15:32
A scheduler for example. Or a task that happens in multiple non consecutive phases.

**Comment by safwansamsudeen** [comment] 2024-04-14 12:44
What do you mean? I'm marking this as a duplicate of #269, but will reopen if needed.

**Closed by safwansamsudeen** 2024-04-14 12:44 UTC
