### ISSUE TITLE
How to make the bar non-interactive?

### ISSUE THREAD

**Issue by scythargon** [frappe/gantt#311] opened 2023-01-25 16:47 UTC
So users won't be able to do anything manually.

And having a bit more documentation than the Readme would be great as well:)

Thanks a lot!

**Comment by green17** [comment] 2023-02-09 20:44
This would be very helpful if we could make s view only mode.

**Comment by m50S79sM6SRNp8Jn** [comment] 2023-08-20 12:48
Can you elaborate what you need exactly, what's your use case?
What does "won't be able to do anything manually" mean to you?
What level of granular does your use case require?

**Comment by scythargon** [comment] 2023-08-25 05:43
Hi!
As far as I can remember - I would like to have an option to prevent any
interactions with the diagram/rows.

вс, 20 авг. 2023 г. в 19:48, m50S79sM6SRNp8Jn ***@***.***>:

**Comment by safwansamsudeen** [comment] 2024-04-04 20:33
Duplicate of #351.

**Closed by safwansamsudeen** 2024-04-04 20:33 UTC
