### ISSUE TITLE
Uncaught TypeError: t is undefined

### ISSUE THREAD

**Issue by LECARROU** [frappe/gantt#477] opened 2024-12-08 20:19 UTC
Trying to use frappe-gantt in my Django projetc.
I have install npm install frappe-gantt and serve dist folder in my Django project : 
    <link` rel="stylesheet" href="{% static 'dist/frappe-gantt.css' %}">
    <script src="{% static 'dist/frappe-gantt.umd.js' %}"></script>
    <div id="gantt" class="gantt-target dark"></div>
Trying to run simple example : 
  <script>
        var tasks = [
        {
            id: 'Task 1',
            name: 'Redesign website',
            start: '2016-12-28',
            end: '2016-12-31',
            progress: 20,
            dependencies: 'Task 2, Task 3',
            custom_class: 'bar-milestone' // optional
        },
        
        ]
        var gantt = new Gantt("#gantt", tasks);
  </script
  
`But got error `Uncaught TypeError: t is undefined`

**Comment by LECARROU** [comment] 2024-12-09 07:59
seems to be due to the way call the constructor. correct code seems to be: var gantt = new Gantt("#gantt", tasks, {});

**Comment by safwansamsudeen** [comment] 2024-12-10 05:03
Thanks for this catch! Fixed now.

**Comment by safwansamsudeen** [comment] 2024-12-10 11:09
I'm trying the same code with the default dict and I don't face this error. Perhaps it's since been updated. I'm leaving this open for now so that you can check again in the new version (to be released soon).

**Comment by LECARROU** [comment] 2024-12-10 11:53
Sorry, I expressed myself badly
In github source code (https://github.com/frappe/gantt/README/), it is mentionned in "start hacking:" section to instanciate Gantt object like this : ```var gantt = new Gantt("#gantt", tasks);```
but in fact, right code should be ```var gantt = new Gantt("#gantt", tasks, {});```

But maybe I missunderstand

**Comment by safwansamsudeen** [comment] 2024-12-16 08:49
@LECARROU, no I understood you. I'm saying that I don't face that error with `var gantt = new Gantt("#gantt", tasks);`.

**Comment by safwansamsudeen** [comment] 2024-12-17 10:49
Closing as can't reproduce.

**Closed by safwansamsudeen** 2024-12-17 10:49 UTC
