### ISSUE TITLE
fixed grid Header when rolling

### ISSUE THREAD

**Issue by piapple** [frappe/gantt#132] opened 2019-04-28 02:31 UTC
fixed grid Header when rolling

**Comment by jcjobin** [comment] 2019-05-03 18:04
For now, I have extended the Gantt class and implemented the changes from this commit: https://github.com/frappe/gantt/pull/100/commits/8b94aa97fdec373ac09d0ae6912e948f8fe9d0a1

**Comment by Blackening999** [comment] 2020-04-20 14:29
Was it solved?
If I scroll too much to the bottom - the header with dates is lost and the whole chart is useless

@netchampfaris 
@swkasica 
@gavindsouza

**Comment by alexscott64** [comment] 2021-01-29 01:40
Was also wondering if anyones converted the changes from 8b94aa9 into something that works. Copying over the code seems to result in issues.

**Comment by medmiskini** [comment] 2021-04-07 12:56
Here's a copy paste solution for those who still need it. https://github.com/medmiskini/gantt/commit/531c5e178449e2a247e5fd5598dc272f7b71cdef

**Comment by SaraBoutej** [comment] 2021-04-07 20:42
> Here's a copy paste solution for those who still need it. [medmiskini@531c5e1](https://github.com/medmiskini/gantt/commit/531c5e178449e2a247e5fd5598dc272f7b71cdef)

thank you so much it works for me!!

**Comment by PriyaBihani** [comment] 2021-09-15 09:27
The code used is old

> Here's a copy paste solution for those who still need it. [medmiskini@531c5e1](https://github.com/medmiskini/gantt/commit/531c5e178449e2a247e5fd5598dc272f7b71cdef)

The code is changed.

**Comment by hammeronthenet** [comment] 2021-10-13 13:56
Ehi! Anyone that is able to adapt @medmiskini solution to new code?

I tried to "merge" but it didn't work!

**Comment by Jveen-D** [comment] 2023-01-11 03:35
> Ehi! Anyone that is able to adapt @medmiskini solution to new code?
> 
> I tried to "merge" but it didn't work!
> 
> EDIT: after futher investigations, the only part on medmiskini solution that didn't works for me is the one on event listener. I change this part in this way:
> 
> ` $.on(this.$container, 'scroll', e => { this.layers.date.setAttribute('transform', 'translate(0,'+ e.currentTarget.scrollTop +')'); }); //STICKY (added)` @PriyaBihani is that what you need?
> 
> Let me know.

It‘s effect,thanks.

![image](https://user-images.githubusercontent.com/46897216/211711786-5f0c82a2-c5ba-4fbf-bf0a-bf6c393a52e0.png)

**Comment by safwansamsudeen** [comment] 2024-04-05 11:17
Duplicate of #115.

**Closed by safwansamsudeen** 2024-04-05 11:17 UTC
