### ISSUE TITLE
is it possible to ?

### ISSUE THREAD

**Issue by jlcurty** [frappe/gantt#23] opened 2017-07-09 16:24 UTC
hi,

I'd like to use frappe/gantt as a graphical planning for rent items ,

is it possible to put several tasks on the same line ? 
is it possible to have a day view ? 

thanks for your support,
Jean-Louis

**Comment by netchampfaris** [comment] 2017-07-19 06:39
@jlcurty Can you provide a mockup?
We already have a Day view mode.

**Comment by Deluxcode-paul** [comment] 2018-02-20 15:05
I also need this. Mockup - http://prntscr.com/ihdhx7

**Comment by safwansamsudeen** [comment] 2024-04-04 20:47
Duplicate of #95.

**Closed by safwansamsudeen** 2024-04-04 20:47 UTC
