### ISSUE TITLE
view year - bug on the end the period

### ISSUE THREAD

**Issue by armure94** [frappe/gantt#198] opened 2020-10-31 08:23 UTC
Hello, 

I have an issue with the view of the year time period bar (the view of the month or the weeks, or day does work, though) in my Gantt diagram. 
The end of the time period bar does not appear at the right place. For instance, as you can see it on the picture, if I choose a time period "01/10/2020 to 31/12/2021, the time period bar stops right berfore 2021 whereas it should stop somewhere between 2021 and 2022. 

![gantt year](https://user-images.githubusercontent.com/50071456/97774603-8c035500-1b59-11eb-8ee7-6527c010624f.png)

Thankyou for your help. 

Pierre

**Comment by tejask432** [comment] 2020-12-29 05:10
for year chart is not working properly

**Comment by safwansamsudeen** [comment] 2024-04-05 11:26
I think this is a duplicate of #313. Please comment if it's not.

**Closed by safwansamsudeen** 2024-04-05 11:26 UTC
