### ISSUE TITLE
Blocking possibility to change progress / date

### ISSUE THREAD

**Issue by lashus** [frappe/gantt#27] opened 2017-09-21 10:16 UTC
Is it possible to set some settings in this library? To be precise - I'm looking for option to block possibility to change progress / date for certain users.

The best case scenerio would be:
new Gantt(container, tasks, {
   canChangeProgress: false,
   canChangeDate: false
});

**Comment by netchampfaris** [comment] 2018-05-20 15:14
This feature should be easy to add. Contributions welcome.

**Comment by safwansamsudeen** [comment] 2024-04-04 20:44
Duplicate of #351.

**Closed** 2024-04-04 20:45 UTC
